Repository OCA/crm, pull requests merged in 2019-05, with the labels that each got.

#268 [FIX] crm_claim: Lint error was fixed
  crm_claim/report/crm_claim_report.py
Labels: approved, needs review

#266 [MIG] crm_claim_code: Migration to 12.0
  crm_claim_code/README.rst
  crm_claim_code/__init__.py
  crm_claim_code/__manifest__.py
  crm_claim_code/data/claim_sequence.xml
  crm_claim_code/hooks.py
  crm_claim_code/i18n/bg.po
  crm_claim_code/i18n/crm_claim_code.pot
  crm_claim_code/i18n/de.po
  crm_claim_code/i18n/es.po
  crm_claim_code/i18n/es_MX.po
  crm_claim_code/i18n/es_VE.po
  crm_claim_code/i18n/fr.po
  crm_claim_code/i18n/hr.po
  crm_claim_code/i18n/nb.po
  crm_claim_code/i18n/pt_BR.po
  crm_claim_code/i18n/sk.po
  crm_claim_code/i18n/sl.po
  crm_claim_code/i18n/sv.po
  crm_claim_code/models/__init__.py
  crm_claim_code/models/crm_claim.py
  crm_claim_code/readme/CONTRIBUTORS.rst
  crm_claim_code/readme/DESCRIPTION.rst
  crm_claim_code/readme/USAGE.rst
  crm_claim_code/static/description/icon.png
  crm_claim_code/tests/__init__.py
  crm_claim_code/tests/test_crm_claim_code.py
  crm_claim_code/views/crm_claim_view.xml
Labels: needs review

#270 [MIG] crm_location_nuts: Migration to 12.0
  crm_location_nuts/README.rst
  crm_location_nuts/__init__.py
  crm_location_nuts/__manifest__.py
  crm_location_nuts/i18n/bg.po
  crm_location_nuts/i18n/crm_location_nuts.pot
  crm_location_nuts/i18n/de.po
  crm_location_nuts/i18n/es.po
  crm_location_nuts/i18n/fr.po
  crm_location_nuts/i18n/hr.po
  crm_location_nuts/i18n/it.po
  crm_location_nuts/i18n/pt_BR.po
  crm_location_nuts/i18n/sk.po
  crm_location_nuts/i18n/sl.po
  crm_location_nuts/i18n/tr.po
  crm_location_nuts/i18n/zh_CN.po
  crm_location_nuts/models/__init__.py
  crm_location_nuts/models/crm_lead.py
  crm_location_nuts/readme/CONTRIBUTORS.rst
  crm_location_nuts/readme/CREDITS.rst
  crm_location_nuts/readme/DESCRIPTION.rst
  crm_location_nuts/readme/ROADMAP.rst
  crm_location_nuts/readme/USAGE.rst
  crm_location_nuts/static/description/icon.png
  crm_location_nuts/static/description/index.html
  crm_location_nuts/tests/__init__.py
  crm_location_nuts/tests/test_crm_location_nuts.py
  crm_location_nuts/views/crm_lead_view.xml
Labels: approved

#272 [12.0] crm_industry: Migration to 12.0
  crm_industry/README.rst
  crm_industry/__init__.py
  crm_industry/__manifest__.py
  crm_industry/i18n/bg.po
  crm_industry/i18n/crm_industry.pot
  crm_industry/i18n/crm_sector.pot
  crm_industry/i18n/de.po
  crm_industry/i18n/es.po
  crm_industry/i18n/fr.po
  crm_industry/i18n/hr.po
  crm_industry/i18n/it.po
  crm_industry/i18n/nb.po
  crm_industry/i18n/nl_NL.po
  crm_industry/i18n/pt_BR.po
  crm_industry/i18n/sk.po
  crm_industry/i18n/sl.po
  crm_industry/i18n/sv.po
  crm_industry/i18n/tr.po
  crm_industry/i18n/tr_TR.po
  crm_industry/i18n/zh_CN.po
  crm_industry/models/__init__.py
  crm_industry/models/crm_lead.py
  crm_industry/readme/CONTRIBUTORS.rst
  crm_industry/readme/DESCRIPTION.rst
  crm_industry/static/description/icon.png
  crm_industry/static/description/index.html
  crm_industry/tests/__init__.py
  crm_industry/tests/test_crm_lead.py
  crm_industry/views/crm_lead_view.xml
Labels: approved

#273 [12.0][MIG] crm_location: Migration to 12.0
  crm_location/README.rst
  crm_location/__init__.py
  crm_location/__manifest__.py
  crm_location/i18n/bg.po
  crm_location/i18n/ca.po
  crm_location/i18n/crm_location.pot
  crm_location/i18n/de.po
  crm_location/i18n/es.po
  crm_location/i18n/es_ES.po
  crm_location/i18n/fi.po
  crm_location/i18n/fr.po
  crm_location/i18n/hr.po
  crm_location/i18n/it.po
  crm_location/i18n/nl_NL.po
  crm_location/i18n/pt_BR.po
  crm_location/i18n/sk.po
  crm_location/i18n/sl.po
  crm_location/i18n/tr.po
  crm_location/i18n/tr_TR.po
  crm_location/i18n/zh_CN.po
  crm_location/models/__init__.py
  crm_location/models/crm_lead.py
  crm_location/readme/CONTRIBUTORS.rst
  crm_location/readme/DESCRIPTION.rst
  crm_location/readme/INSTALL.rst
  crm_location/static/description/icon.png
  crm_location/static/description/index.html
  crm_location/tests/__init__.py
  crm_location/tests/test_crm_location.py
  crm_location/views/crm_lead_view.xml
Labels: approved
