Repository OCA/crm, pull requests merged in 2020-06, with the labels that each got.

#333 [13.0][MIG] crm_meeting_commercial_partner: Migration to 13.0
  crm_meeting_commercial_partner/README.rst
  crm_meeting_commercial_partner/__init__.py
  crm_meeting_commercial_partner/__manifest__.py
  crm_meeting_commercial_partner/i18n/crm_meeting_commercial_partner.pot
  crm_meeting_commercial_partner/models/__init__.py
  crm_meeting_commercial_partner/models/res_partner.py
  crm_meeting_commercial_partner/readme/CONTRIBUTORS.rst
  crm_meeting_commercial_partner/readme/DESCRIPTION.rst
  crm_meeting_commercial_partner/readme/USAGE.rst
  crm_meeting_commercial_partner/static/description/icon.png
  crm_meeting_commercial_partner/static/description/index.html
  crm_meeting_commercial_partner/tests/__init__.py
  crm_meeting_commercial_partner/tests/test_crm_meeting_commercial_partner.py
  setup/crm_meeting_commercial_partner/odoo/addons/crm_meeting_commercial_partner
  setup/crm_meeting_commercial_partner/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#337 [12.0][FIX] crm_phonecall: Remove New Mail filter
  crm_phonecall/views/crm_phonecall_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#331 [13.0][FIX] Clean up license links
  crm_lead_firstname/__init__.py
  crm_lead_firstname/__manifest__.py
  crm_lead_firstname/models/__init__.py
  crm_lead_firstname/models/crm_lead.py
  crm_lead_firstname/tests/__init__.py
  crm_lead_firstname/tests/test_crm_lead.py
  crm_lead_firstname/views/crm_lead_view.xml
  crm_lead_product/__init__.py
  crm_lead_product/__manifest__.py
  crm_lead_product/models/__init__.py
  crm_lead_product/models/crm_lead.py
  crm_lead_product/models/crm_lead_line.py
  crm_lead_product/report/__init__.py
  crm_lead_product/report/crm_product_report.py
  crm_lead_product/tests/__init__.py
  crm_lead_product/tests/test_crm_lead_line.py
  crm_lead_vat/__init__.py
  crm_lead_vat/__manifest__.py
  crm_lead_vat/models/__init__.py
  crm_lead_vat/models/crm_lead.py
  crm_lead_vat/tests/__init__.py
  crm_lead_vat/tests/test_lead.py
  crm_location/__init__.py
  crm_location/__manifest__.py
  crm_location/models/__init__.py
  crm_location/models/crm_lead.py
  crm_location/tests/__init__.py
  crm_location/tests/test_crm_location.py
  crm_phonecall/__manifest__.py
  crm_phonecall/models/calendar.py
  crm_phonecall/models/crm_lead.py
  crm_phonecall/models/crm_phonecall.py
  crm_phonecall/models/res_partner.py
  crm_phonecall/report/crm_phonecall_report.py
  crm_phonecall/tests/test_crm_phonecall.py
  crm_phonecall/wizard/crm_phonecall_to_phonecall.py
Labels: approved, bot is merging ⏳, ready to merge

#296 [13.0][MIG] crm_lead_code
  crm_lead_code/README.rst
  crm_lead_code/__init__.py
  crm_lead_code/__manifest__.py
  crm_lead_code/data/lead_sequence.xml
  crm_lead_code/i18n/bg.po
  crm_lead_code/i18n/crm_lead_code.pot
  crm_lead_code/i18n/de.po
  crm_lead_code/i18n/es.po
  crm_lead_code/i18n/fr.po
  crm_lead_code/i18n/hr.po
  crm_lead_code/i18n/it.po
  crm_lead_code/i18n/pt_BR.po
  crm_lead_code/i18n/sk.po
  crm_lead_code/i18n/sl.po
  crm_lead_code/i18n/tr.po
  crm_lead_code/i18n/zh_CN.po
  crm_lead_code/models/__init__.py
  crm_lead_code/models/crm_lead.py
  crm_lead_code/readme/CONTRIBUTORS.rst
  crm_lead_code/readme/DESCRIPTION.rst
  crm_lead_code/static/description/icon.png
  crm_lead_code/static/description/index.html
  crm_lead_code/tests/__init__.py
  crm_lead_code/tests/test_crm_lead_code.py
  crm_lead_code/views/crm_lead_view.xml
  setup/crm_lead_code/odoo/addons/crm_lead_code
  setup/crm_lead_code/setup.py
Labels: bot is merging ⏳

#316 [13.0][MIG] crm_claim
  crm_claim/README.rst
  crm_claim/__init__.py
  crm_claim/__manifest__.py
  crm_claim/data/crm_claim_data.xml
  crm_claim/demo/crm_claim_demo.xml
  crm_claim/i18n/crm_claim.pot
  crm_claim/i18n/de.po
  crm_claim/i18n/es.po
  crm_claim/i18n/es_CO.po
  crm_claim/i18n/gl.po
  crm_claim/i18n/hr.po
  crm_claim/i18n/pt_BR.po
  crm_claim/models/__init__.py
  crm_claim/models/crm_claim.py
  crm_claim/models/crm_claim_category.py
  crm_claim/models/crm_claim_stage.py
  crm_claim/models/res_partner.py
  crm_claim/readme/CONFIGURE.rst
  crm_claim/readme/CONTRIBUTORS.rst
  crm_claim/readme/DESCRIPTION.rst
  crm_claim/readme/HISTORY.rst
  crm_claim/readme/USAGE.rst
  crm_claim/report/__init__.py
  crm_claim/report/crm_claim_report.py
  crm_claim/report/crm_claim_report_view.xml
  crm_claim/security/crm_claim_security.xml
  crm_claim/security/ir.model.access.csv
  crm_claim/static/description/icon.png
  crm_claim/static/description/index.html
  crm_claim/tests/__init__.py
  crm_claim/tests/test_crm_claim.py
  crm_claim/views/crm_claim_category_views.xml
  crm_claim/views/crm_claim_menu.xml
  crm_claim/views/crm_claim_stage_views.xml
  crm_claim/views/crm_claim_views.xml
  crm_claim/views/res_partner_views.xml
  setup/crm_claim/odoo/addons/crm_claim
  setup/crm_claim/setup.py
Labels: approved, bot is merging ⏳

#338 [13.0][FIX] crm_phonecall: Remove New Mail filter
  crm_phonecall/views/crm_phonecall_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#342 [ADD] crm_l10n_eu_nace: NACE for leads
  crm_l10n_eu_nace/README.rst
  crm_l10n_eu_nace/__init__.py
  crm_l10n_eu_nace/__manifest__.py
  crm_l10n_eu_nace/i18n/es.po
  crm_l10n_eu_nace/models/__init__.py
  crm_l10n_eu_nace/models/crm_lead.py
  crm_l10n_eu_nace/readme/CONTRIBUTORS.rst
  crm_l10n_eu_nace/readme/DESCRIPTION.rst
  crm_l10n_eu_nace/readme/INSTALL.rst
  crm_l10n_eu_nace/static/description/icon.png
  crm_l10n_eu_nace/static/description/index.html
  crm_l10n_eu_nace/tests/__init__.py
  crm_l10n_eu_nace/tests/test_crm_nace.py
  crm_l10n_eu_nace/views/crm_lead_view.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳
