Repository OCA/crm, pull requests merged in 2020-05, with the labels that each got.

#325 [11.0][FIX] Update travis to latest template
  .travis.yml
Labels: bug

#322 [13.0][IMP] crm_phonecall: Add field direction in calls and improve views.
  crm_phonecall/__manifest__.py
  crm_phonecall/models/__init__.py
  crm_phonecall/models/crm_phonecall.py
  crm_phonecall/models/res_config_settings.py
  crm_phonecall/readme/CONTRIBUTORS.rst
  crm_phonecall/security/crm_security.xml
  crm_phonecall/views/crm_phonecall_view.xml
  crm_phonecall/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#327 [IMP][13.0] crm_phonecall: improvement for inheritance
  crm_phonecall/models/crm_phonecall.py
  crm_phonecall/tests/test_crm_phonecall.py
  crm_phonecall/wizard/crm_phonecall_to_phonecall.py
  crm_phonecall/wizard/crm_phonecall_to_phonecall_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#320 [11.0][FIX] crm_meeting_commercial_partner: fix context for schedule_meeting action
  crm_meeting_commercial_partner/models/res_partner.py
Labels: bot is merging ⏳, enhancement, needs review
