Repository OCA/crm, pull requests merged in 2020-07, with the labels that each got.

#343 [FIX] crm_claim: Claim statusbar not clickable
  crm_claim/views/crm_claim_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#334 [13.0][MIG] crm_industry: Migration to 13.0
  crm_industry/README.rst
  crm_industry/__init__.py
  crm_industry/__manifest__.py
  crm_industry/i18n/bg.po
  crm_industry/i18n/ca.po
  crm_industry/i18n/ca_ES.po
  crm_industry/i18n/crm_industry.pot
  crm_industry/i18n/crm_sector.pot
  crm_industry/i18n/de.po
  crm_industry/i18n/es.po
  crm_industry/i18n/fr.po
  crm_industry/i18n/hr.po
  crm_industry/i18n/it.po
  crm_industry/i18n/nb.po
  crm_industry/i18n/nl_NL.po
  crm_industry/i18n/pt_BR.po
  crm_industry/i18n/sk.po
  crm_industry/i18n/sl.po
  crm_industry/i18n/sv.po
  crm_industry/i18n/tr.po
  crm_industry/i18n/tr_TR.po
  crm_industry/i18n/zh_CN.po
  crm_industry/models/__init__.py
  crm_industry/models/crm_lead.py
  crm_industry/readme/CONTRIBUTORS.rst
  crm_industry/readme/DESCRIPTION.rst
  crm_industry/static/description/icon.png
  crm_industry/static/description/index.html
  crm_industry/tests/__init__.py
  crm_industry/tests/test_crm_lead.py
  crm_industry/views/crm_lead_view.xml
  setup/crm_industry/odoo/addons/crm_industry
  setup/crm_industry/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#328 [12.0][IMP] crm_stage_type: add missing tests
  crm_stage_type/tests/test_crm_stage_type.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#323 [13.0][MIG] crm_stage_type: Migration to 13.0
  crm_stage_type/README.rst
  crm_stage_type/__init__.py
  crm_stage_type/__manifest__.py
  crm_stage_type/i18n/crm_stage_type.pot
  crm_stage_type/i18n/sl.po
  crm_stage_type/models/__init__.py
  crm_stage_type/models/crm_lead.py
  crm_stage_type/models/crm_stage.py
  crm_stage_type/readme/CONTRIBUTORS.rst
  crm_stage_type/readme/DESCRIPTION.rst
  crm_stage_type/static/description/icon.png
  crm_stage_type/static/description/index.html
  crm_stage_type/tests/__init__.py
  crm_stage_type/tests/test_crm_stage_type.py
  crm_stage_type/views/crm_lead_views.xml
  crm_stage_type/views/crm_stage_views.xml
  setup/crm_stage_type/odoo/addons/crm_stage_type
  setup/crm_stage_type/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#326 [12.0][IMP] crm_phonecall: Add field direction in calls and improve views
  crm_phonecall/README.rst
  crm_phonecall/__manifest__.py
  crm_phonecall/models/__init__.py
  crm_phonecall/models/crm_phonecall.py
  crm_phonecall/models/res_config_settings.py
  crm_phonecall/readme/CONTRIBUTORS.rst
  crm_phonecall/readme/USAGE.rst
  crm_phonecall/security/crm_security.xml
  crm_phonecall/static/description/index.html
  crm_phonecall/tests/test_crm_phonecall.py
  crm_phonecall/views/crm_phonecall_view.xml
  crm_phonecall/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#244 [12.0] add crm team parent field
  crm_team_parent/__init__.py
  crm_team_parent/__manifest__.py
  crm_team_parent/models/__init__.py
  crm_team_parent/models/crm_team.py
  crm_team_parent/readme/CONTRIBUTORS.rst
  crm_team_parent/readme/DESCRIPTION.rst
  crm_team_parent/readme/USAGE.rst
  crm_team_parent/static/description/icon.png
  crm_team_parent/tests/__init__.py
  crm_team_parent/tests/test_crm_team_parent.py
  crm_team_parent/views/crm_team.xml
  setup/crm_team_parent/odoo/addons/crm_team_parent
  setup/crm_team_parent/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge
