Repository OCA/crm, pull requests merged in 2020-08, with the labels that each got.

#347 Fix Case of Domain is None
  crm_stage_type/models/crm_lead.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#330 [12.0][FIX] crm_phonecall_planner: fix sql injection
  crm_phonecall_planner/wizards/crm_phonecall_planner.py
Labels: approved, bot is merging ⏳, ready to merge

#345 [12.0][IMP] crm_phonecall: Add in/out crm_phonecall filters
  crm_phonecall/views/crm_phonecall_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#349 crm_phonecall: Phonecall statusbar not clickable
  crm_phonecall/views/crm_phonecall_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#351 [12.0] Fix coverage badge and add addons table
  README.md
Labels: approved, bot is merging ⏳

#353 [10.0] Fix coverage badge
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#352 [11.0] Fix coverage badge and add addons table
  README.md
Labels: approved, bot is merging ⏳, ready to merge

#350 [13.0] Fix coverage badge and add addons table
  README.md
Labels: approved, bot is merging ⏳, ready to merge
