Repository OCA/crm, pull requests merged in 2021-06, with the labels that each got.

#368 [MIG] crm_lead_vat: Migration to 14.0
  crm_lead_vat/README.rst
  crm_lead_vat/__init__.py
  crm_lead_vat/__manifest__.py
  crm_lead_vat/i18n/bg.po
  crm_lead_vat/i18n/crm_lead_vat.pot
  crm_lead_vat/i18n/de.po
  crm_lead_vat/i18n/es.po
  crm_lead_vat/i18n/fr.po
  crm_lead_vat/i18n/hr.po
  crm_lead_vat/i18n/it.po
  crm_lead_vat/i18n/pt_BR.po
  crm_lead_vat/i18n/sk.po
  crm_lead_vat/i18n/sl.po
  crm_lead_vat/i18n/zh_CN.po
  crm_lead_vat/models/__init__.py
  crm_lead_vat/models/crm_lead.py
  crm_lead_vat/readme/CONTRIBUTORS.rst
  crm_lead_vat/readme/DESCRIPTION.rst
  crm_lead_vat/readme/USAGE.rst
  crm_lead_vat/static/description/icon.png
  crm_lead_vat/static/description/index.html
  crm_lead_vat/tests/__init__.py
  crm_lead_vat/tests/test_lead.py
  crm_lead_vat/views/crm_lead_views.xml
  setup/crm_lead_vat/odoo/addons/crm_lead_vat
  setup/crm_lead_vat/setup.py
Labels: bot is merging ⏳

#372 14.0 mig crm location
  crm_location/README.rst
  crm_location/__init__.py
  crm_location/__manifest__.py
  crm_location/i18n/bg.po
  crm_location/i18n/ca.po
  crm_location/i18n/crm_location.pot
  crm_location/i18n/de.po
  crm_location/i18n/es.po
  crm_location/i18n/es_ES.po
  crm_location/i18n/fi.po
  crm_location/i18n/fr.po
  crm_location/i18n/hr.po
  crm_location/i18n/it.po
  crm_location/i18n/nl_NL.po
  crm_location/i18n/pt_BR.po
  crm_location/i18n/sk.po
  crm_location/i18n/sl.po
  crm_location/i18n/tr.po
  crm_location/i18n/tr_TR.po
  crm_location/i18n/zh_CN.po
  crm_location/models/__init__.py
  crm_location/models/crm_lead.py
  crm_location/readme/CONTRIBUTORS.rst
  crm_location/readme/DESCRIPTION.rst
  crm_location/readme/INSTALL.rst
  crm_location/static/description/icon.png
  crm_location/static/description/index.html
  crm_location/tests/__init__.py
  crm_location/tests/test_crm_location.py
  crm_location/views/crm_lead_view.xml
  setup/crm_location/odoo/addons/crm_location
  setup/crm_location/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#391 [14.0][MIG] crm_claim: Migration to 14.0
  crm_claim/README.rst
  crm_claim/__init__.py
  crm_claim/__manifest__.py
  crm_claim/data/crm_claim_data.xml
  crm_claim/demo/crm_claim_demo.xml
  crm_claim/i18n/crm_claim.pot
  crm_claim/i18n/de.po
  crm_claim/i18n/es.po
  crm_claim/i18n/es_CO.po
  crm_claim/i18n/gl.po
  crm_claim/i18n/hr.po
  crm_claim/i18n/pt_BR.po
  crm_claim/models/__init__.py
  crm_claim/models/crm_claim.py
  crm_claim/models/crm_claim_category.py
  crm_claim/models/crm_claim_stage.py
  crm_claim/models/res_partner.py
  crm_claim/readme/CONFIGURE.rst
  crm_claim/readme/CONTRIBUTORS.rst
  crm_claim/readme/DESCRIPTION.rst
  crm_claim/readme/HISTORY.rst
  crm_claim/readme/USAGE.rst
  crm_claim/report/__init__.py
  crm_claim/report/crm_claim_report.py
  crm_claim/report/crm_claim_report_view.xml
  crm_claim/security/crm_claim_security.xml
  crm_claim/security/ir.model.access.csv
  crm_claim/static/description/icon.png
  crm_claim/static/description/index.html
  crm_claim/tests/__init__.py
  crm_claim/tests/test_crm_claim.py
  crm_claim/views/crm_claim_category_views.xml
  crm_claim/views/crm_claim_menu.xml
  crm_claim/views/crm_claim_stage_views.xml
  crm_claim/views/crm_claim_views.xml
  crm_claim/views/res_partner_views.xml
  setup/crm_claim/odoo/addons/crm_claim
  setup/crm_claim/setup.py
Labels: approved, bot is merging ⏳, ready to merge
