Repository OCA/crm, pull requests merged in 2021-01, with the labels that each got.

#373 [12.0][ADD] crm_secondary_salesperson
  crm_secondary_salesperson/README.rst
  crm_secondary_salesperson/__init__.py
  crm_secondary_salesperson/__manifest__.py
  crm_secondary_salesperson/i18n/crm_secondary_salesperson.pot
  crm_secondary_salesperson/i18n/pt_BR.po
  crm_secondary_salesperson/models/__init__.py
  crm_secondary_salesperson/models/crm_lead.py
  crm_secondary_salesperson/readme/CONFIGURE.rst
  crm_secondary_salesperson/readme/CONTRIBUTORS.rst
  crm_secondary_salesperson/readme/DESCRIPTION.rst
  crm_secondary_salesperson/readme/USAGE.rst
  crm_secondary_salesperson/static/description/banner.png
  crm_secondary_salesperson/static/description/icon.png
  crm_secondary_salesperson/static/description/index.html
  crm_secondary_salesperson/views/crm_lead.xml
Labels: approved, bot is merging ⏳, ready to merge

#367 14.0 mig crm lead firstname
  crm_lead_firstname/README.rst
  crm_lead_firstname/__init__.py
  crm_lead_firstname/__manifest__.py
  crm_lead_firstname/i18n/bg.po
  crm_lead_firstname/i18n/crm_lead_firstname.pot
  crm_lead_firstname/i18n/de.po
  crm_lead_firstname/i18n/es.po
  crm_lead_firstname/i18n/fr.po
  crm_lead_firstname/i18n/fr_CH.po
  crm_lead_firstname/i18n/hr.po
  crm_lead_firstname/i18n/it.po
  crm_lead_firstname/i18n/pt_BR.po
  crm_lead_firstname/i18n/sk.po
  crm_lead_firstname/i18n/sl.po
  crm_lead_firstname/i18n/tr.po
  crm_lead_firstname/i18n/zh_CN.po
  crm_lead_firstname/models/__init__.py
  crm_lead_firstname/models/crm_lead.py
  crm_lead_firstname/readme/CONTRIBUTORS.rst
  crm_lead_firstname/readme/DESCRIPTION.rst
  crm_lead_firstname/readme/INSTALL.rst
  crm_lead_firstname/readme/USAGE.rst
  crm_lead_firstname/static/description/icon.png
  crm_lead_firstname/static/description/index.html
  crm_lead_firstname/tests/__init__.py
  crm_lead_firstname/tests/test_crm_lead.py
  crm_lead_firstname/views/crm_lead_view.xml
  setup/crm_lead_firstname/odoo/addons/crm_lead_firstname
  setup/crm_lead_firstname/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#379 [13.0][MIG] crm_claim_code: Migration to 13.0
  crm_claim_code/README.rst
  crm_claim_code/__init__.py
  crm_claim_code/__manifest__.py
  crm_claim_code/data/claim_sequence.xml
  crm_claim_code/hooks.py
  crm_claim_code/i18n/bg.po
  crm_claim_code/i18n/crm_claim_code.pot
  crm_claim_code/i18n/de.po
  crm_claim_code/i18n/es.po
  crm_claim_code/i18n/es_MX.po
  crm_claim_code/i18n/es_VE.po
  crm_claim_code/i18n/fr.po
  crm_claim_code/i18n/hr.po
  crm_claim_code/i18n/it.po
  crm_claim_code/i18n/nb.po
  crm_claim_code/i18n/pt_BR.po
  crm_claim_code/i18n/sk.po
  crm_claim_code/i18n/sl.po
  crm_claim_code/i18n/sv.po
  crm_claim_code/models/__init__.py
  crm_claim_code/models/crm_claim.py
  crm_claim_code/readme/CONTRIBUTORS.rst
  crm_claim_code/readme/DESCRIPTION.rst
  crm_claim_code/readme/USAGE.rst
  crm_claim_code/static/description/icon.png
  crm_claim_code/static/description/index.html
  crm_claim_code/tests/__init__.py
  crm_claim_code/tests/test_crm_claim_code.py
  crm_claim_code/views/crm_claim_view.xml
  setup/crm_claim_code/odoo/addons/crm_claim_code
  setup/crm_claim_code/setup.py
Labels: approved, bot is merging ⏳, migration, needs review
