Repository OCA/crm, pull requests merged in 2022-02, with the labels that each got.

#417 [14.0][MIG] crm_l10n_eu_nace: Migration to 14.0
  crm_l10n_eu_nace/README.rst
  crm_l10n_eu_nace/__init__.py
  crm_l10n_eu_nace/__manifest__.py
  crm_l10n_eu_nace/i18n/crm_l10n_eu_nace.pot
  crm_l10n_eu_nace/i18n/es.po
  crm_l10n_eu_nace/models/__init__.py
  crm_l10n_eu_nace/models/crm_lead.py
  crm_l10n_eu_nace/readme/CONTRIBUTORS.rst
  crm_l10n_eu_nace/readme/DESCRIPTION.rst
  crm_l10n_eu_nace/readme/INSTALL.rst
  crm_l10n_eu_nace/static/description/icon.png
  crm_l10n_eu_nace/static/description/index.html
  crm_l10n_eu_nace/tests/__init__.py
  crm_l10n_eu_nace/tests/test_crm_nace.py
  crm_l10n_eu_nace/views/crm_lead_view.xml
  oca_dependencies.txt
  setup/crm_l10n_eu_nace/odoo/addons/crm_l10n_eu_nace
  setup/crm_l10n_eu_nace/setup.py
Labels: approved, bot is merging ⏳

#410 [13.0][ADD] crm_salesperson_planner
  crm_salesperson_planner/__init__.py
  crm_salesperson_planner/__manifest__.py
  crm_salesperson_planner/data/crm_salesperson_planner_sequence.xml
  crm_salesperson_planner/data/ir_cron_data.xml
  crm_salesperson_planner/i18n/es.po
  crm_salesperson_planner/models/__init__.py
  crm_salesperson_planner/models/calendar_event.py
  crm_salesperson_planner/models/crm_lead.py
  crm_salesperson_planner/models/crm_salesperson_planner_visit.py
  crm_salesperson_planner/models/crm_salesperson_planner_visit_close_reason.py
  crm_salesperson_planner/models/crm_salesperson_planner_visit_template.py
  crm_salesperson_planner/models/res_partner.py
  crm_salesperson_planner/readme/CONFIGURE.rst
  crm_salesperson_planner/readme/CONTRIBUTORS.rst
  crm_salesperson_planner/readme/DESCRIPTION.rst
  crm_salesperson_planner/readme/USAGE.rst
  crm_salesperson_planner/security/crm_salesperson_planner_security.xml
  crm_salesperson_planner/security/ir.model.access.csv
  crm_salesperson_planner/static/description/icon.png
  crm_salesperson_planner/static/description/index.html
  crm_salesperson_planner/tests/__init__.py
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit.py
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit_template.py
  crm_salesperson_planner/views/crm_lead.xml
  crm_salesperson_planner/views/crm_salesperson_planner_menu.xml
  crm_salesperson_planner/views/crm_salesperson_planner_visit_close_reason_views.xml
  crm_salesperson_planner/views/crm_salesperson_planner_visit_template_views.xml
  crm_salesperson_planner/views/crm_salesperson_planner_visit_views.xml
  crm_salesperson_planner/views/res_partner.xml
  crm_salesperson_planner/wizards/__init__.py
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_close_wiz.py
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_close_wiz_view.xml
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_template_create.py
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_template_create.xml
  setup/crm_salesperson_planner/odoo/addons/crm_salesperson_planner
  setup/crm_salesperson_planner/setup.py
Labels: needs review, bot is merging ⏳

#265 [ADD][12.0] crm_lead_currency
  crm_lead_currency/__init__.py
  crm_lead_currency/__manifest__.py
  crm_lead_currency/models/__init__.py
  crm_lead_currency/models/crm_lead.py
  crm_lead_currency/readme/CONFIGURE.rst
  crm_lead_currency/readme/CONTRIBUTORS.rst
  crm_lead_currency/readme/DESCRIPTION.rst
  crm_lead_currency/readme/INSTALL.rst
  crm_lead_currency/readme/USAGE.rst
  crm_lead_currency/static/description/icon.png
  crm_lead_currency/tests/__init__.py
  crm_lead_currency/tests/test_crm_opportunity_currency.py
  crm_lead_currency/views/crm_lead_opportunity_currency_views.xml
Labels: needs review, bot is merging ⏳, stale
