Repository OCA/crm, pull requests merged in 2022-10, with the labels that each got.

#433 [15.0][MIG] crm_stage_probability
  crm_stage_probability/README.rst
  crm_stage_probability/__init__.py
  crm_stage_probability/__manifest__.py
  crm_stage_probability/data/crm_stage.xml
  crm_stage_probability/i18n/crm_stage_probability.pot
  crm_stage_probability/models/__init__.py
  crm_stage_probability/models/crm_lead.py
  crm_stage_probability/models/crm_stage.py
  crm_stage_probability/readme/CONFIGURE.rst
  crm_stage_probability/readme/CONTRIBUTORS.rst
  crm_stage_probability/readme/DESCRIPTION.rst
  crm_stage_probability/security/ir.model.access.csv
  crm_stage_probability/static/description/icon.png
  crm_stage_probability/static/description/index.html
  crm_stage_probability/tests/__init__.py
  crm_stage_probability/tests/test_crm_lead_probability.py
  crm_stage_probability/views/crm_lead.xml
  crm_stage_probability/views/crm_stage.xml
  crm_stage_probability/wizard/__init__.py
  crm_stage_probability/wizard/crm_lead_stage_probability_update.py
  crm_stage_probability/wizard/crm_lead_stage_probability_update.xml
  setup/crm_stage_probability/odoo/addons/crm_stage_probability
  setup/crm_stage_probability/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#446 [13.0][IMP] crm_project: Copy email_cc from lead to task.
  crm_project/tests/test_crm_project.py
  crm_project/wizard/crm_lead_convert2task.py
Labels: approved, bot is merging ⏳

#447 [14.0][IMP] crm_project: Copy email_cc from lead to task.
  crm_project/tests/test_crm_project.py
  crm_project/wizard/crm_lead_convert2task.py
Labels: approved, bot is merging ⏳

#449 [15.0][IMP] crm_project: Copy email_cc from lead to task.
  crm_project/tests/test_crm_project.py
  crm_project/wizard/crm_lead_convert2task.py
Labels: bot is merging ⏳
