Repository OCA/crm, pull requests merged in 2022-09, with the labels that each got.

#436 [13.0][DCK] Updated from template
  .copier-answers.yml
  .eslintrc.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  crm_claim/__manifest__.py
  crm_lead_firstname/__manifest__.py
  crm_lead_product/__manifest__.py
  crm_project/__manifest__.py
  crm_secondary_salesperson/__manifest__.py
  crm_security_group/__manifest__.py
  marketing_crm_partner/__manifest__.py
Labels: bot is merging ⏳

#435 [13.0][IMP] crm_claim: Remove unnecessary (and confusing) activity fields in views (form + tree).
  crm_claim/i18n/crm_claim.pot
  crm_claim/i18n/es.po
  crm_claim/views/crm_claim_views.xml
Labels: approved, bot is merging ⏳

#438 [14.0][DCK] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: bot is merging ⏳

#437 [14.0][IMP] crm_claim: Remove unnecessary (and confusing) activity fields in views (form + tree).
  crm_claim/i18n/crm_claim.pot
  crm_claim/i18n/es.po
  crm_claim/views/crm_claim_views.xml
Labels: approved, bot is merging ⏳

#439 [15.0][IMP] crm_claim: Remove unnecessary (and confusing) activity fields in views (form + tree).
  crm_claim/i18n/crm_claim.pot
  crm_claim/i18n/es.po
  crm_claim/views/crm_claim_views.xml
Labels: approved, bot is merging ⏳

#425 [14.0][IMP] crm_phonecall: cleanup convert2opportunity action
  crm_phonecall/models/crm_phonecall.py
  crm_phonecall/tests/test_crm_phonecall.py
Labels: bot is merging ⏳, stale

#440 [15.0][IMP] crm_phonecall: cleanup convert2opportunity action
  crm_phonecall/models/crm_phonecall.py
  crm_phonecall/tests/test_crm_phonecall.py
Labels: bot is merging ⏳
