Repository OCA/crm, pull requests merged in 2022-11, with the labels that each got.

#454 [13.0][FIX] crm_security_group: Fix menu visibility
  crm_security_group/security/security.xml
  crm_security_group/tests/test_crm_security.py
  crm_security_group/views/menu_items.xml
Labels: approved, bot is merging ⏳

#453 [14.0][FIX] crm_security_group: Fix menu visibility
  crm_security_group/security/security.xml
  crm_security_group/tests/test_crm_security.py
  crm_security_group/views/menu_items.xml
Labels: approved, bot is merging ⏳

#451 [15.0][MIG] crm_security_group: Migration to 15.0
  crm_security_group/README.rst
  crm_security_group/__init__.py
  crm_security_group/__manifest__.py
  crm_security_group/i18n/crm_security_group.pot
  crm_security_group/readme/CONTRIBUTORS.rst
  crm_security_group/readme/DESCRIPTION.rst
  crm_security_group/readme/ROADMAP.rst
  crm_security_group/security/ir.model.access.csv
  crm_security_group/security/security.xml
  crm_security_group/static/description/icon.png
  crm_security_group/static/description/index.html
  crm_security_group/tests/__init__.py
  crm_security_group/tests/test_crm_security.py
  crm_security_group/views/menu_items.xml
  setup/crm_security_group/odoo/addons/crm_security_group
  setup/crm_security_group/setup.py
Labels: approved, bot is merging ⏳

#455 [15.0][FIX] crm_security_group: Set groups_id in menu items correctly (similar to v14)
  crm_security_group/views/menu_items.xml
Labels: bot is merging ⏳

#441 [MIG] crm_lead_firstname: Migration to 15.0
  crm_lead_firstname/README.rst
  crm_lead_firstname/__init__.py
  crm_lead_firstname/__manifest__.py
  crm_lead_firstname/i18n/bg.po
  crm_lead_firstname/i18n/crm_lead_firstname.pot
  crm_lead_firstname/i18n/de.po
  crm_lead_firstname/i18n/es.po
  crm_lead_firstname/i18n/es_AR.po
  crm_lead_firstname/i18n/fr.po
  crm_lead_firstname/i18n/fr_CH.po
  crm_lead_firstname/i18n/hr.po
  crm_lead_firstname/i18n/it.po
  crm_lead_firstname/i18n/pt_BR.po
  crm_lead_firstname/i18n/sk.po
  crm_lead_firstname/i18n/sl.po
  crm_lead_firstname/i18n/tr.po
  crm_lead_firstname/i18n/zh_CN.po
  crm_lead_firstname/models/__init__.py
  crm_lead_firstname/models/crm_lead.py
  crm_lead_firstname/readme/CONTRIBUTORS.rst
  crm_lead_firstname/readme/DESCRIPTION.rst
  crm_lead_firstname/readme/INSTALL.rst
  crm_lead_firstname/readme/USAGE.rst
  crm_lead_firstname/static/description/icon.png
  crm_lead_firstname/static/description/index.html
  crm_lead_firstname/tests/__init__.py
  crm_lead_firstname/tests/test_crm_lead.py
  crm_lead_firstname/views/crm_lead_view.xml
  oca_dependencies.txt
  setup/crm_lead_firstname/odoo/addons/crm_lead_firstname
  setup/crm_lead_firstname/setup.py
Labels: approved, bot is merging ⏳

#459 [15.0][MIG] crm_salesperson_planner: Migration to 15.0
  crm_salesperson_planner/README.rst
  crm_salesperson_planner/__init__.py
  crm_salesperson_planner/__manifest__.py
  crm_salesperson_planner/data/crm_salesperson_planner_sequence.xml
  crm_salesperson_planner/data/ir_cron_data.xml
  crm_salesperson_planner/i18n/crm_salesperson_planner.pot
  crm_salesperson_planner/i18n/es.po
  crm_salesperson_planner/migrations/15.0.1.0.0/pre-migration.py
  crm_salesperson_planner/models/__init__.py
  crm_salesperson_planner/models/calendar_event.py
  crm_salesperson_planner/models/crm_lead.py
  crm_salesperson_planner/models/crm_salesperson_planner_visit.py
  crm_salesperson_planner/models/crm_salesperson_planner_visit_close_reason.py
  crm_salesperson_planner/models/crm_salesperson_planner_visit_template.py
  crm_salesperson_planner/models/res_partner.py
  crm_salesperson_planner/readme/CONFIGURE.rst
  crm_salesperson_planner/readme/CONTRIBUTORS.rst
  crm_salesperson_planner/readme/DESCRIPTION.rst
  crm_salesperson_planner/readme/USAGE.rst
  crm_salesperson_planner/security/crm_salesperson_planner_security.xml
  crm_salesperson_planner/security/ir.model.access.csv
  crm_salesperson_planner/static/description/icon.png
  crm_salesperson_planner/static/description/index.html
  crm_salesperson_planner/tests/__init__.py
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit.py
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit_template.py
  crm_salesperson_planner/views/crm_lead.xml
  crm_salesperson_planner/views/crm_salesperson_planner_menu.xml
  crm_salesperson_planner/views/crm_salesperson_planner_visit_close_reason_views.xml
  crm_salesperson_planner/views/crm_salesperson_planner_visit_template_views.xml
  crm_salesperson_planner/views/crm_salesperson_planner_visit_views.xml
  crm_salesperson_planner/views/res_partner.xml
  crm_salesperson_planner/wizards/__init__.py
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_close_wiz.py
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_close_wiz_view.xml
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_template_create.py
  crm_salesperson_planner/wizards/crm_salesperson_planner_visit_template_create.xml
  setup/crm_salesperson_planner/odoo/addons/crm_salesperson_planner
  setup/crm_salesperson_planner/setup.py
Labels: approved, bot is merging ⏳

#464 [15.0][ADD] crm_salesperson_planner_sale: New module
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit.py
  crm_salesperson_planner_sale/README.rst
  crm_salesperson_planner_sale/__init__.py
  crm_salesperson_planner_sale/__manifest__.py
  crm_salesperson_planner_sale/i18n/crm_salesperson_planner_sale.pot
  crm_salesperson_planner_sale/i18n/es.po
  crm_salesperson_planner_sale/models/__init__.py
  crm_salesperson_planner_sale/models/crm_salesperson_planner_visit.py
  crm_salesperson_planner_sale/models/sale_order.py
  crm_salesperson_planner_sale/readme/CONTRIBUTORS.rst
  crm_salesperson_planner_sale/readme/DESCRIPTION.rst
  crm_salesperson_planner_sale/readme/USAGE.rst
  crm_salesperson_planner_sale/static/description/icon.png
  crm_salesperson_planner_sale/static/description/index.html
  crm_salesperson_planner_sale/tests/__init__.py
  crm_salesperson_planner_sale/tests/test_crm_salesperson_planner_sale.py
  crm_salesperson_planner_sale/views/crm_salesperson_planner_visit_views.xml
  crm_salesperson_planner_sale/views/sale_order_views.xml
  setup/crm_salesperson_planner_sale/odoo/addons/crm_salesperson_planner_sale
  setup/crm_salesperson_planner_sale/setup.py
Labels: approved, bot is merging ⏳

#456 [15.0][FIX] crm_lead_firstname: missing contact_lastname when quick create is used
  crm_lead_firstname/views/crm_lead_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
