Repository OCA/crm, pull requests merged in 2022-12, with the labels that each got.

#465 ADD 14.0 module crm_lead_search_archive
  crm_lead_search_archive/README.rst
  crm_lead_search_archive/__init__.py
  crm_lead_search_archive/__manifest__.py
  crm_lead_search_archive/i18n/crm_lead_search_archive.pot
  crm_lead_search_archive/i18n/fr.po
  crm_lead_search_archive/readme/CONTRIBUTORS.rst
  crm_lead_search_archive/readme/DESCRIPTION.rst
  crm_lead_search_archive/views/crm_lead_view.xml
  setup/crm_lead_search_archive/odoo/addons/crm_lead_search_archive
  setup/crm_lead_search_archive/setup.py
Labels: approved, bot is merging ⏳

#458 [12.0] update dotfiles
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  crm_claim/__manifest__.py
  crm_lead_code/__manifest__.py
  crm_lead_currency/views/crm_lead_opportunity_currency_views.xml
  crm_lead_firstname/__manifest__.py
  crm_lead_product/__manifest__.py
  crm_location_nuts/__manifest__.py
  crm_sale_secondary_salesperson/__manifest__.py
  crm_secondary_salesperson/readme/DESCRIPTION.rst
  crm_secondary_salesperson/readme/USAGE.rst
  crm_team_parent/tests/test_crm_team_parent.py
  marketing_crm_partner/__manifest__.py
Labels: bot is merging ⏳

#468 [16.0][MIG] crm_claim: Migration to 16.0
  crm_claim/README.rst
  crm_claim/__init__.py
  crm_claim/__manifest__.py
  crm_claim/data/crm_claim_data.xml
  crm_claim/demo/crm_claim_demo.xml
  crm_claim/i18n/ca.po
  crm_claim/i18n/crm_claim.pot
  crm_claim/i18n/de.po
  crm_claim/i18n/es.po
  crm_claim/i18n/es_CO.po
  crm_claim/i18n/gl.po
  crm_claim/i18n/hr.po
  crm_claim/i18n/pt_BR.po
  crm_claim/models/__init__.py
  crm_claim/models/crm_claim.py
  crm_claim/models/crm_claim_category.py
  crm_claim/models/crm_claim_stage.py
  crm_claim/models/res_partner.py
  crm_claim/readme/CONFIGURE.rst
  crm_claim/readme/CONTRIBUTORS.rst
  crm_claim/readme/DESCRIPTION.rst
  crm_claim/readme/HISTORY.rst
  crm_claim/readme/USAGE.rst
  crm_claim/report/__init__.py
  crm_claim/report/crm_claim_report.py
  crm_claim/report/crm_claim_report_view.xml
  crm_claim/security/crm_claim_security.xml
  crm_claim/security/ir.model.access.csv
  crm_claim/static/description/icon.png
  crm_claim/static/description/index.html
  crm_claim/tests/__init__.py
  crm_claim/tests/test_crm_claim.py
  crm_claim/views/crm_claim_category_views.xml
  crm_claim/views/crm_claim_menu.xml
  crm_claim/views/crm_claim_stage_views.xml
  crm_claim/views/crm_claim_views.xml
  crm_claim/views/res_partner_views.xml
  setup/crm_claim/odoo/addons/crm_claim
  setup/crm_claim/setup.py
Labels: approved, ready to merge, bot is merging ⏳
