Repository OCA/crm, pull requests merged in 2023-02, with the labels that each got.

#475 [15.0] Update pre-commit conf
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: needs review, approved

#473 [15.0][FIX] crm_multicompany_reporting_currency: fix amount
  crm_multicompany_reporting_currency/__manifest__.py
  crm_multicompany_reporting_currency/models/crm_lead.py
  crm_multicompany_reporting_currency/tests/test_amount_multicompany_reporting_currency.py
Labels: approved, ready to merge, bot is merging ⏳

#424 [15.0][ADD] crm_won_reason
  crm_won_reason/README.rst
  crm_won_reason/__init__.py
  crm_won_reason/__manifest__.py
  crm_won_reason/models/__init__.py
  crm_won_reason/models/crm_lead.py
  crm_won_reason/models/crm_lost_reason.py
  crm_won_reason/readme/CONTRIBUTORS.rst
  crm_won_reason/readme/DESCRIPTION.rst
  crm_won_reason/security/ir.model.access.csv
  crm_won_reason/static/description/index.html
  crm_won_reason/tests/__init__.py
  crm_won_reason/tests/test_crm_lead_reason.py
  crm_won_reason/views/crm_views.xml
  crm_won_reason/wizard/__init__.py
  crm_won_reason/wizard/crm_lead_lost.py
  crm_won_reason/wizard/crm_lead_won.py
  crm_won_reason/wizard/crm_lead_won.xml
  setup/crm_won_reason/odoo/addons/crm_won_reason
  setup/crm_won_reason/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#442 [ADD] crm_industry: Propagate industries from customer to lead/opportunity
  crm_industry/__manifest__.py
  crm_industry/models/crm_lead.py
  crm_industry/readme/CONTRIBUTORS.rst
  crm_industry/tests/test_crm_lead.py
Labels: needs review, approved, bot is merging ⏳, stale

#478 [15.0][FIX] crm_phonecall: Fix error element "schedule_meeting" not found in parent view
  crm_phonecall/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
