Repository OCA/crm, pull requests merged in 2023-08, with the labels that each got.

#512 [15.0][IMP] crm_partner_assign: move fields before user_id
  crm_partner_assign/readme/CONTRIBUTORS.rst
  crm_partner_assign/views/crm_lead_view.xml
Labels: needs review, approved, bot is merging ⏳

#511 [15.0][IMP][crm_lead_vat] Sync vat between partner and lead
  crm_lead_vat/models/crm_lead.py
  crm_lead_vat/readme/CONTRIBUTORS.rst
  crm_lead_vat/readme/USAGE.rst
  crm_lead_vat/tests/test_lead.py
  crm_lead_vat/views/crm_lead_views.xml
Labels: needs review, approved, bot is merging ⏳

#514 [16.0][mig] crm_project_task
  crm_project_task/README.rst
  crm_project_task/__init__.py
  crm_project_task/__manifest__.py
  crm_project_task/i18n/crm_project_task.pot
  crm_project_task/i18n/es.po
  crm_project_task/i18n/it.po
  crm_project_task/models/__init__.py
  crm_project_task/models/crm_lead.py
  crm_project_task/models/project_task.py
  crm_project_task/models/res_company.py
  crm_project_task/models/res_config_settings.py
  crm_project_task/readme/CONFIGURE.rst
  crm_project_task/readme/CONTRIBUTORS.rst
  crm_project_task/readme/DESCRIPTION.rst
  crm_project_task/readme/USAGE.rst
  crm_project_task/security/ir.model.access.csv
  crm_project_task/static/description/icon.png
  crm_project_task/static/description/index.html
  crm_project_task/tests/__init__.py
  crm_project_task/tests/test_crm_project_task.py
  crm_project_task/views/crm_lead.xml
  crm_project_task/views/project_task.xml
  crm_project_task/views/res_config_settings.xml
  crm_project_task/wizards/__init__.py
  crm_project_task/wizards/crm_create_task.py
  crm_project_task/wizards/crm_create_task.xml
  setup/crm_project_task/odoo/addons/crm_project_task
  setup/crm_project_task/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#517 [14.0][TEMP] crm_location_nuts: do not run tests as it makes all CI pipelines to fail
  crm_location_nuts/tests/__init__.py
Labels: bot is merging ⏳
