Repository OCA/crm, pull requests merged in 2023-03, with the labels that each got.

#477 [16.0][MIG] crm_lead_code: Migration to 16.0
  crm_lead_code/README.rst
  crm_lead_code/__init__.py
  crm_lead_code/__manifest__.py
  crm_lead_code/data/lead_sequence.xml
  crm_lead_code/i18n/bg.po
  crm_lead_code/i18n/ca.po
  crm_lead_code/i18n/crm_lead_code.pot
  crm_lead_code/i18n/de.po
  crm_lead_code/i18n/es.po
  crm_lead_code/i18n/es_AR.po
  crm_lead_code/i18n/fr.po
  crm_lead_code/i18n/hr.po
  crm_lead_code/i18n/it.po
  crm_lead_code/i18n/pt_BR.po
  crm_lead_code/i18n/sk.po
  crm_lead_code/i18n/sl.po
  crm_lead_code/i18n/tr.po
  crm_lead_code/i18n/zh_CN.po
  crm_lead_code/models/__init__.py
  crm_lead_code/models/crm_lead.py
  crm_lead_code/readme/CONTRIBUTORS.rst
  crm_lead_code/readme/DESCRIPTION.rst
  crm_lead_code/static/description/icon.png
  crm_lead_code/static/description/index.html
  crm_lead_code/tests/__init__.py
  crm_lead_code/tests/test_crm_lead_code.py
  crm_lead_code/views/crm_lead_view.xml
  setup/crm_lead_code/odoo/addons/crm_lead_code
  setup/crm_lead_code/setup.py
Labels: needs review, bot is merging ⏳

#461 [MIG] crm_lead_firstname: Migration to 16.0
  crm_lead_firstname/README.rst
  crm_lead_firstname/__init__.py
  crm_lead_firstname/__manifest__.py
  crm_lead_firstname/i18n/bg.po
  crm_lead_firstname/i18n/crm_lead_firstname.pot
  crm_lead_firstname/i18n/de.po
  crm_lead_firstname/i18n/es.po
  crm_lead_firstname/i18n/es_AR.po
  crm_lead_firstname/i18n/fr.po
  crm_lead_firstname/i18n/fr_CH.po
  crm_lead_firstname/i18n/hr.po
  crm_lead_firstname/i18n/it.po
  crm_lead_firstname/i18n/pt_BR.po
  crm_lead_firstname/i18n/sk.po
  crm_lead_firstname/i18n/sl.po
  crm_lead_firstname/i18n/tr.po
  crm_lead_firstname/i18n/zh_CN.po
  crm_lead_firstname/models/__init__.py
  crm_lead_firstname/models/crm_lead.py
  crm_lead_firstname/readme/CONTRIBUTORS.rst
  crm_lead_firstname/readme/DESCRIPTION.rst
  crm_lead_firstname/readme/INSTALL.rst
  crm_lead_firstname/readme/USAGE.rst
  crm_lead_firstname/static/description/icon.png
  crm_lead_firstname/static/description/index.html
  crm_lead_firstname/tests/__init__.py
  crm_lead_firstname/tests/test_crm_lead.py
  crm_lead_firstname/views/crm_lead_view.xml
  setup/crm_lead_firstname/odoo/addons/crm_lead_firstname
  setup/crm_lead_firstname/setup.py
Labels: needs review, approved, bot is merging ⏳

#457 [12.0][ADD] crm_klaviyo
  crm_klaviyo/README.rst
  crm_klaviyo/__init__.py
  crm_klaviyo/__manifest__.py
  crm_klaviyo/models/__init__.py
  crm_klaviyo/models/klaviyo_account.py
  crm_klaviyo/readme/CONFIGURE.rst
  crm_klaviyo/readme/CONTRIBUTORS.rst
  crm_klaviyo/readme/DESCRIPTION.rst
  crm_klaviyo/readme/USAGE.rst
  crm_klaviyo/security/ir.model.access.csv
  crm_klaviyo/static/description/icon.png
  crm_klaviyo/static/description/icon.svg
  crm_klaviyo/static/description/index.html
  crm_klaviyo/tests/__init__.py
  crm_klaviyo/tests/test_crm_klaviyo.py
  crm_klaviyo/views/klaviyo_account.xml
  requirements.txt
  setup/crm_klaviyo/odoo/addons/crm_klaviyo
  setup/crm_klaviyo/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#467 [16.0] [MIG] crm_lead_search_archive
  crm_lead_search_archive/README.rst
  crm_lead_search_archive/__init__.py
  crm_lead_search_archive/__manifest__.py
  crm_lead_search_archive/i18n/crm_lead_search_archive.pot
  crm_lead_search_archive/i18n/fr.po
  crm_lead_search_archive/readme/CONTRIBUTORS.rst
  crm_lead_search_archive/readme/DESCRIPTION.rst
  crm_lead_search_archive/static/description/icon.png
  crm_lead_search_archive/static/description/index.html
  crm_lead_search_archive/views/crm_lead_view.xml
  setup/crm_lead_search_archive/odoo/addons/crm_lead_search_archive
  setup/crm_lead_search_archive/setup.py
Labels: needs review, approved, bot is merging ⏳

#405 [14.0][FIX] Fixes crm lead code : we can define our sequence for multi-company
  crm_lead_code/models/crm_lead.py
Labels: needs review, approved, bot is merging ⏳, no stale

#483 [FIX] klaviyo_crm: allow installing requirements on python 3.5
  .copier-answers.yml
  .pre-commit-config.yaml
  requirements.txt
Labels: needs review, approved, bot is merging ⏳

#482 [15.0][MIG] crm_lead_vat: Migration to version 15.0
  crm_lead_vat/README.rst
  crm_lead_vat/__init__.py
  crm_lead_vat/__manifest__.py
  crm_lead_vat/i18n/bg.po
  crm_lead_vat/i18n/crm_lead_vat.pot
  crm_lead_vat/i18n/de.po
  crm_lead_vat/i18n/es.po
  crm_lead_vat/i18n/fr.po
  crm_lead_vat/i18n/hr.po
  crm_lead_vat/i18n/it.po
  crm_lead_vat/i18n/pt_BR.po
  crm_lead_vat/i18n/sk.po
  crm_lead_vat/i18n/sl.po
  crm_lead_vat/i18n/zh_CN.po
  crm_lead_vat/models/__init__.py
  crm_lead_vat/models/crm_lead.py
  crm_lead_vat/readme/CONTRIBUTORS.rst
  crm_lead_vat/readme/DESCRIPTION.rst
  crm_lead_vat/readme/USAGE.rst
  crm_lead_vat/static/description/icon.png
  crm_lead_vat/static/description/index.html
  crm_lead_vat/tests/__init__.py
  crm_lead_vat/tests/test_lead.py
  crm_lead_vat/views/crm_lead_views.xml
  setup/crm_lead_vat/odoo/addons/crm_lead_vat
  setup/crm_lead_vat/setup.py
Labels: approved, bot is merging ⏳
