Repository OCA/crm, pull requests merged in 2023-06, with the labels that each got.

#493 [16.0][MIG] crm_industry
  crm_industry/README.rst
  crm_industry/__init__.py
  crm_industry/__manifest__.py
  crm_industry/i18n/bg.po
  crm_industry/i18n/ca.po
  crm_industry/i18n/ca_ES.po
  crm_industry/i18n/crm_industry.pot
  crm_industry/i18n/crm_sector.pot
  crm_industry/i18n/de.po
  crm_industry/i18n/es.po
  crm_industry/i18n/fr.po
  crm_industry/i18n/hr.po
  crm_industry/i18n/it.po
  crm_industry/i18n/nb.po
  crm_industry/i18n/nl_NL.po
  crm_industry/i18n/pt_BR.po
  crm_industry/i18n/sk.po
  crm_industry/i18n/sl.po
  crm_industry/i18n/sv.po
  crm_industry/i18n/tr.po
  crm_industry/i18n/tr_TR.po
  crm_industry/i18n/zh_CN.po
  crm_industry/models/__init__.py
  crm_industry/models/crm_lead.py
  crm_industry/readme/CONTRIBUTORS.rst
  crm_industry/readme/DESCRIPTION.rst
  crm_industry/static/description/icon.png
  crm_industry/static/description/index.html
  crm_industry/tests/__init__.py
  crm_industry/tests/test_crm_lead.py
  crm_industry/views/crm_lead_view.xml
  setup/crm_industry/odoo/addons/crm_industry
  setup/crm_industry/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#503 [15.0][FIX] crm_security_group: Add ACL from crm.lead.lost to group_crm_own_leads
  crm_security_group/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#502 [16.0][MIG] crm_lead_currency: Migration to 16.0
  crm_lead_currency/README.rst
  crm_lead_currency/__init__.py
  crm_lead_currency/__manifest__.py
  crm_lead_currency/i18n/crm_lead_currency.pot
  crm_lead_currency/i18n/es.po
  crm_lead_currency/i18n/it.po
  crm_lead_currency/models/__init__.py
  crm_lead_currency/models/crm_lead.py
  crm_lead_currency/readme/CONFIGURE.rst
  crm_lead_currency/readme/CONTRIBUTORS.rst
  crm_lead_currency/readme/DESCRIPTION.rst
  crm_lead_currency/readme/INSTALL.rst
  crm_lead_currency/readme/USAGE.rst
  crm_lead_currency/static/description/icon.png
  crm_lead_currency/static/description/index.html
  crm_lead_currency/tests/__init__.py
  crm_lead_currency/tests/test_crm_opportunity_currency.py
  crm_lead_currency/views/crm_lead_views.xml
  setup/crm_lead_currency/odoo/addons/crm_lead_currency
  setup/crm_lead_currency/setup.py
Labels: bot is merging ⏳
