Repository OCA/crm, pull requests merged in 2024-07, with the labels that each got.

#578 [15.0][MIG] crm_claim_code: Migration to 15.0
  crm_claim_code/README.rst
  crm_claim_code/__init__.py
  crm_claim_code/__manifest__.py
  crm_claim_code/data/claim_sequence.xml
  crm_claim_code/hooks.py
  crm_claim_code/i18n/bg.po
  crm_claim_code/i18n/crm_claim_code.pot
  crm_claim_code/i18n/de.po
  crm_claim_code/i18n/es.po
  crm_claim_code/i18n/es_MX.po
  crm_claim_code/i18n/es_VE.po
  crm_claim_code/i18n/fr.po
  crm_claim_code/i18n/hr.po
  crm_claim_code/i18n/it.po
  crm_claim_code/i18n/nb.po
  crm_claim_code/i18n/pt_BR.po
  crm_claim_code/i18n/sk.po
  crm_claim_code/i18n/sl.po
  crm_claim_code/i18n/sv.po
  crm_claim_code/models/__init__.py
  crm_claim_code/models/crm_claim.py
  crm_claim_code/readme/CONTRIBUTORS.rst
  crm_claim_code/readme/DESCRIPTION.rst
  crm_claim_code/readme/USAGE.rst
  crm_claim_code/static/description/icon.png
  crm_claim_code/static/description/index.html
  crm_claim_code/tests/__init__.py
  crm_claim_code/tests/test_crm_claim_code.py
  crm_claim_code/views/crm_claim_view.xml
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit_template.py
  setup/crm_claim_code/odoo/addons/crm_claim_code
  setup/crm_claim_code/setup.py
Labels: approved, bot is merging ⏳

#582 [17.0][MIG] crm_lead_currency: Migration to 17.0
  crm_lead_currency/README.rst
  crm_lead_currency/__init__.py
  crm_lead_currency/__manifest__.py
  crm_lead_currency/i18n/crm_lead_currency.pot
  crm_lead_currency/i18n/es.po
  crm_lead_currency/i18n/it.po
  crm_lead_currency/models/__init__.py
  crm_lead_currency/models/crm_lead.py
  crm_lead_currency/pyproject.toml
  crm_lead_currency/readme/CONFIGURE.md
  crm_lead_currency/readme/CONTRIBUTORS.md
  crm_lead_currency/readme/DESCRIPTION.md
  crm_lead_currency/readme/INSTALL.md
  crm_lead_currency/readme/USAGE.md
  crm_lead_currency/static/description/icon.png
  crm_lead_currency/static/description/index.html
  crm_lead_currency/tests/__init__.py
  crm_lead_currency/tests/test_crm_opportunity_currency.py
  crm_lead_currency/views/crm_lead_views.xml
Labels: approved, migration, bot is merging ⏳

#587 [15.0][FIX] crm_project: Don't remove old lead, but archive
  crm_project/tests/test_crm_project.py
  crm_project/wizard/crm_lead_convert2task.py
Labels: approved

#590 [16.0][FIX] crm_salesperson_planner: Fix tests (Add freeze_time decorator to make it more resilient)
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit_template.py
Labels: bot is merging ⏳

#577 [16.0][ADD] crm_create_project: Allow create project from lead or opportunity
  crm_project_create/README.rst
  crm_project_create/__init__.py
  crm_project_create/__manifest__.py
  crm_project_create/i18n/crm_project_create.pot
  crm_project_create/i18n/es.po
  crm_project_create/models/__init__.py
  crm_project_create/models/crm_lead.py
  crm_project_create/readme/CONTEXT.md
  crm_project_create/readme/CONTRIBUTORS.md
  crm_project_create/readme/DESCRIPTION.md
  crm_project_create/readme/USAGE.md
  crm_project_create/security/ir.model.access.csv
  crm_project_create/static/description/icon.png
  crm_project_create/static/description/index.html
  crm_project_create/tests/__init__.py
  crm_project_create/tests/test_crm_create_project.py
  crm_project_create/views/crm_lead.xml
  crm_project_create/wizards/__init__.py
  crm_project_create/wizards/crm_create_project.py
  crm_project_create/wizards/crm_create_project.xml
  setup/crm_project_create/odoo/addons/crm_project_create
  setup/crm_project_create/setup.py
Labels: bot is merging ⏳
