Repository OCA/crm, pull requests merged in 2025-05, with the labels that each got.

#645 [16.0][ADD] crm_date_deadline_required: New module
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  crm_date_deadline_required/README.rst
  crm_date_deadline_required/__init__.py
  crm_date_deadline_required/__manifest__.py
  crm_date_deadline_required/readme/CONTEXT.md
  crm_date_deadline_required/readme/CONTRIBUTORS.md
  crm_date_deadline_required/readme/DESCRIPTION.md
  crm_date_deadline_required/readme/USAGE.md
  crm_date_deadline_required/static/description/icon.png
  crm_date_deadline_required/static/description/index.html
  crm_date_deadline_required/tests/__init__.py
  crm_date_deadline_required/tests/test_crm_date_deadline_required.py
  crm_date_deadline_required/views/crm_lead_view.xml
  setup/crm_date_deadline_required/odoo/addons/crm_date_deadline_required
  setup/crm_date_deadline_required/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#647 [16.0][ADD] crm_partner_required: New module
  .copier-answers.yml
  .github/workflows/test.yml
  crm_partner_required/README.rst
  crm_partner_required/__init__.py
  crm_partner_required/__manifest__.py
  crm_partner_required/readme/CONTEXT.md
  crm_partner_required/readme/CONTRIBUTORS.md
  crm_partner_required/readme/DESCRIPTION.md
  crm_partner_required/readme/USAGE.md
  crm_partner_required/static/description/icon.png
  crm_partner_required/static/description/index.html
  crm_partner_required/tests/__init__.py
  crm_partner_required/tests/test_crm_partner_required.py
  crm_partner_required/views/crm_lead_view.xml
  setup/crm_partner_required/odoo/addons/crm_partner_required
  setup/crm_partner_required/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#648 [18.0][MIG] crm_lead_product: Migration 18.0
  crm_lead_product/README.rst
  crm_lead_product/__init__.py
  crm_lead_product/__manifest__.py
  crm_lead_product/i18n/ca.po
  crm_lead_product/i18n/ca_ES.po
  crm_lead_product/i18n/crm_lead_product.pot
  crm_lead_product/i18n/es.po
  crm_lead_product/i18n/it.po
  crm_lead_product/models/__init__.py
  crm_lead_product/models/crm_lead.py
  crm_lead_product/models/crm_lead_line.py
  crm_lead_product/pyproject.toml
  crm_lead_product/readme/CONFIGURE.md
  crm_lead_product/readme/CONTRIBUTORS.md
  crm_lead_product/readme/DESCRIPTION.md
  crm_lead_product/readme/USAGE.md
  crm_lead_product/report/__init__.py
  crm_lead_product/report/crm_product_report.py
  crm_lead_product/report/crm_product_report_views.xml
  crm_lead_product/security/ir.model.access.csv
  crm_lead_product/static/description/icon.png
  crm_lead_product/static/description/index.html
  crm_lead_product/tests/__init__.py
  crm_lead_product/tests/test_crm_lead_line.py
  crm_lead_product/views/crm_lead_line_views.xml
  crm_lead_product/views/crm_lead_views.xml
Labels: approved, bot is merging ⏳

#630 [MIG][18.0] Migration of crm_project_create from 16.0
  crm_project_create/README.rst
  crm_project_create/__init__.py
  crm_project_create/__manifest__.py
  crm_project_create/i18n/crm_project_create.pot
  crm_project_create/i18n/es.po
  crm_project_create/i18n/it.po
  crm_project_create/models/__init__.py
  crm_project_create/models/crm_lead.py
  crm_project_create/pyproject.toml
  crm_project_create/readme/CONTEXT.md
  crm_project_create/readme/CONTRIBUTORS.md
  crm_project_create/readme/DESCRIPTION.md
  crm_project_create/readme/USAGE.md
  crm_project_create/security/ir.model.access.csv
  crm_project_create/static/description/icon.png
  crm_project_create/static/description/index.html
  crm_project_create/tests/__init__.py
  crm_project_create/tests/test_crm_create_project.py
  crm_project_create/views/crm_lead.xml
  crm_project_create/wizards/__init__.py
  crm_project_create/wizards/crm_create_project.py
  crm_project_create/wizards/crm_create_project.xml
Labels: approved, migration, bot is merging ⏳
