Repository OCA/crm, pull requests merged in 2025-03, with the labels that each got.

#633 [17.0][FIX] crm_salesperson_planner: fix unit tests
  crm_salesperson_planner/tests/test_crm_salesperson_planner_visit_template.py
  crm_salesperson_planner/views/crm_salesperson_planner_visit_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#634 [18.0][FIX]crm_phonecall: Fixed invisible opportunity issue
  crm_phonecall/views/crm_phonecall_view.xml
Labels: approved, bot is merging ⏳

#606 [17.0][MIG] crm_partner_assign: Migration to 17.0
  crm_partner_assign/README.rst
  crm_partner_assign/__init__.py
  crm_partner_assign/__manifest__.py
  crm_partner_assign/i18n/crm_partner_assign.pot
  crm_partner_assign/i18n/es.po
  crm_partner_assign/i18n/it.po
  crm_partner_assign/models/__init__.py
  crm_partner_assign/models/crm_lead.py
  crm_partner_assign/models/res_partner.py
  crm_partner_assign/pyproject.toml
  crm_partner_assign/readme/CONTRIBUTORS.md
  crm_partner_assign/readme/CREDITS.md
  crm_partner_assign/readme/DESCRIPTION.md
  crm_partner_assign/readme/INSTALL.md
  crm_partner_assign/readme/USAGE.md
  crm_partner_assign/static/description/icon.png
  crm_partner_assign/static/description/index.html
  crm_partner_assign/tests/__init__.py
  crm_partner_assign/tests/test_crm_lead.py
  crm_partner_assign/views/crm_lead_view.xml
  crm_partner_assign/views/res_partner_view.xml
Labels: needs review, approved, migration, bot is merging ⏳

#609 [MIG] crm_lead_code: Migration to 18.0
  crm_lead_code/README.rst
  crm_lead_code/__init__.py
  crm_lead_code/__manifest__.py
  crm_lead_code/data/lead_sequence.xml
  crm_lead_code/i18n/bg.po
  crm_lead_code/i18n/ca.po
  crm_lead_code/i18n/crm_lead_code.pot
  crm_lead_code/i18n/de.po
  crm_lead_code/i18n/es.po
  crm_lead_code/i18n/es_AR.po
  crm_lead_code/i18n/fr.po
  crm_lead_code/i18n/hr.po
  crm_lead_code/i18n/it.po
  crm_lead_code/i18n/pt_BR.po
  crm_lead_code/i18n/sk.po
  crm_lead_code/i18n/sl.po
  crm_lead_code/i18n/tr.po
  crm_lead_code/i18n/zh_CN.po
  crm_lead_code/models/__init__.py
  crm_lead_code/models/crm_lead.py
  crm_lead_code/pyproject.toml
  crm_lead_code/readme/CONTRIBUTORS.md
  crm_lead_code/readme/DESCRIPTION.md
  crm_lead_code/static/description/icon.png
  crm_lead_code/static/description/index.html
  crm_lead_code/tests/__init__.py
  crm_lead_code/tests/test_crm_lead_code.py
  crm_lead_code/views/crm_lead_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#637 [18.0][FIX] crm_phonecall: prevent access error to ir.actions.act_window for normal users
  crm_phonecall/models/crm_lead.py
Labels: approved, bot is merging ⏳

#638 [18.0][MIG] crm_won_restrict_per_stage: Migration to 18.0
  crm_won_restrict_per_stage/README.rst
  crm_won_restrict_per_stage/__init__.py
  crm_won_restrict_per_stage/__manifest__.py
  crm_won_restrict_per_stage/i18n/crm_won_restrict_per_stage.pot
  crm_won_restrict_per_stage/i18n/es.po
  crm_won_restrict_per_stage/i18n/it.po
  crm_won_restrict_per_stage/models/__init__.py
  crm_won_restrict_per_stage/models/crm_lead.py
  crm_won_restrict_per_stage/models/crm_stage.py
  crm_won_restrict_per_stage/pyproject.toml
  crm_won_restrict_per_stage/readme/CONFIGURE.md
  crm_won_restrict_per_stage/readme/CONTRIBUTORS.md
  crm_won_restrict_per_stage/readme/DESCRIPTION.md
  crm_won_restrict_per_stage/static/description/icon.png
  crm_won_restrict_per_stage/static/description/index.html
  crm_won_restrict_per_stage/tests/__init__.py
  crm_won_restrict_per_stage/tests/test_crm_lead.py
  crm_won_restrict_per_stage/views/crm_lead_views.xml
  crm_won_restrict_per_stage/views/crm_stage_views.xml
Labels: approved, bot is merging ⏳

#636 [18.0][MIG] crm_security_group: Migration to 18.0
  crm_security_group/README.rst
  crm_security_group/__init__.py
  crm_security_group/__manifest__.py
  crm_security_group/i18n/crm_security_group.pot
  crm_security_group/i18n/es.po
  crm_security_group/i18n/it.po
  crm_security_group/pyproject.toml
  crm_security_group/readme/CONTRIBUTORS.md
  crm_security_group/readme/DESCRIPTION.md
  crm_security_group/readme/ROADMAP.md
  crm_security_group/security/ir.model.access.csv
  crm_security_group/security/security.xml
  crm_security_group/static/description/icon.png
  crm_security_group/static/description/index.html
  crm_security_group/tests/__init__.py
  crm_security_group/tests/test_crm_security.py
  crm_security_group/views/crm_lead_views.xml
  crm_security_group/views/crm_team_views.xml
  crm_security_group/views/menu_items.xml
Labels: approved, ready to merge, bot is merging ⏳
