Repository OCA/crm, pull requests merged in 2025-02, with the labels that each got.

#604 [18.0][MIG] crm_lead_firstname: Migration to 18.0
  crm_lead_firstname/README.rst
  crm_lead_firstname/__init__.py
  crm_lead_firstname/__manifest__.py
  crm_lead_firstname/i18n/bg.po
  crm_lead_firstname/i18n/crm_lead_firstname.pot
  crm_lead_firstname/i18n/de.po
  crm_lead_firstname/i18n/es.po
  crm_lead_firstname/i18n/es_AR.po
  crm_lead_firstname/i18n/fr.po
  crm_lead_firstname/i18n/fr_CH.po
  crm_lead_firstname/i18n/hr.po
  crm_lead_firstname/i18n/it.po
  crm_lead_firstname/i18n/pt_BR.po
  crm_lead_firstname/i18n/sk.po
  crm_lead_firstname/i18n/sl.po
  crm_lead_firstname/i18n/tr.po
  crm_lead_firstname/i18n/zh_CN.po
  crm_lead_firstname/models/__init__.py
  crm_lead_firstname/models/crm_lead.py
  crm_lead_firstname/pyproject.toml
  crm_lead_firstname/readme/CONTRIBUTORS.md
  crm_lead_firstname/readme/DESCRIPTION.md
  crm_lead_firstname/readme/INSTALL.md
  crm_lead_firstname/readme/USAGE.md
  crm_lead_firstname/static/description/icon.png
  crm_lead_firstname/static/description/index.html
  crm_lead_firstname/tests/__init__.py
  crm_lead_firstname/tests/test_crm_lead.py
  crm_lead_firstname/views/crm_lead_view.xml
Labels: approved, bot is merging ⏳

#631 [16.0][IMP] crm_project_create: Archive or reactive the project and its analytical account from lead.
  crm_project_create/README.rst
  crm_project_create/models/crm_lead.py
  crm_project_create/readme/CONTRIBUTORS.md
  crm_project_create/readme/DESCRIPTION.md
  crm_project_create/static/description/index.html
  crm_project_create/tests/test_crm_create_project.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#605 [18.0][MIG] crm_stage_probability: Migration to 18.0
  crm_stage_probability/README.rst
  crm_stage_probability/__init__.py
  crm_stage_probability/__manifest__.py
  crm_stage_probability/data/crm_stage.xml
  crm_stage_probability/i18n/crm_stage_probability.pot
  crm_stage_probability/i18n/es.po
  crm_stage_probability/i18n/it.po
  crm_stage_probability/i18n/nl.po
  crm_stage_probability/models/__init__.py
  crm_stage_probability/models/crm_lead.py
  crm_stage_probability/models/crm_stage.py
  crm_stage_probability/pyproject.toml
  crm_stage_probability/readme/CONFIGURE.md
  crm_stage_probability/readme/CONTRIBUTORS.md
  crm_stage_probability/readme/DESCRIPTION.md
  crm_stage_probability/security/ir.model.access.csv
  crm_stage_probability/static/description/icon.png
  crm_stage_probability/static/description/index.html
  crm_stage_probability/tests/__init__.py
  crm_stage_probability/tests/test_crm_lead_probability.py
  crm_stage_probability/views/crm_lead.xml
  crm_stage_probability/views/crm_stage.xml
  crm_stage_probability/wizard/__init__.py
  crm_stage_probability/wizard/crm_lead_stage_probability_update.py
  crm_stage_probability/wizard/crm_lead_stage_probability_update.xml
Labels: approved, ready to merge, bot is merging ⏳
